#!/opt/local/bin/python
from __future__ import print_function
import argparse
import datetime
from mskpy import ephem, util

today = datetime.date.today()

parser = argparse.ArgumentParser(description='Generate an ephemeris.')
parser.add_argument('target', type=str, action='store', nargs='*',
                    help='The name of the target')
parser.add_argument('--start', type=str, action='store',
                    default=today.isoformat(),
                    help='The first day of the ephemeris [today].')
parser.add_argument('--end', type=str, action='store', default=None,
                    help='The last day of the ephemeris [today + n].')
parser.add_argument('-n', type=int, action='store', default=30,
                    help='The number of days for the ephemeris.')

args = parser.parse_args()

if args.end is None:
    end = datetime.date.fromordinal(today.toordinal() + args.n).isoformat()
    n = args.n + 1
else:
    end = args.end
    n = util.cal2time(end).jd - util.cal2time(args.start).jd + 1

target = ephem.getspiceobj(' '.join(args.target))

t = target.ephemeris(ephem.Earth, [args.start, end], num=n)
t.pprint(max_width=-1, max_lines=-1)

